/**
 * Preset queries for the interactive playground.
 *
 * @module presets
 */

import type { Preset } from "../types/analysis";

/** Default preset loaded on page init. */
export const DEFAULT_PRESET_ID = "simple";

/** Display order for preset buttons. */
export const PRESET_ORDER = [
  "simple",
  "attack",
  "fragment",
  "ignore",
  "recursion",
  "introspection",
];

/** All available presets, alphabetically ordered by id. */
export const PRESETS: Preset[] = [
  {
    description: "Recursive 5-level nesting that exceeds the max depth",
    id: "attack",
    label: "Deep / Attack",
    options: { ignore: [], ignoreIntrospection: "typename", maxDepth: 3 },
    query: [
      "query DeepAttack {",
      '  user(id: "1") {',
      "    friends {",
      "      friends {",
      "        friends {",
      "          friends {",
      "            friends {",
      "              name",
      "            }",
      "          }",
      "        }",
      "      }",
      "    }",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    description: "Named and inline fragments with depth tracking",
    id: "fragment",
    label: "Fragment",
    options: { ignore: [], ignoreIntrospection: "typename", maxDepth: 4 },
    query: [
      "query WithFragments {",
      '  user(id: "1") {',
      "    ...UserFields",
      "    ... on Admin {",
      "      role",
      "      permissions {",
      "        scope",
      "      }",
      "    }",
      "  }",
      "}",
      "",
      "fragment UserFields on User {",
      "  name",
      "  posts {",
      "    title",
      "    comments {",
      "      text",
      "    }",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    description: "Field excluded from depth counting via ignore rules",
    id: "ignore",
    label: "Ignore",
    options: { ignore: ["metadata"], ignoreIntrospection: "typename", maxDepth: 3 },
    query: [
      "query WithIgnore {",
      '  user(id: "1") {',
      "    metadata {",
      "      internalId",
      "    }",
      "    posts {",
      "      title",
      "      comments {",
      "        text",
      "        author {",
      "          name",
      "        }",
      "      }",
      "    }",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    description: "Schema introspection with all __ fields ignored",
    id: "introspection",
    label: "Introspection",
    options: { ignore: [], ignoreIntrospection: "all", maxDepth: 3 },
    query: [
      "query IntrospectionQuery {",
      "  __schema {",
      "    types {",
      "      name",
      "      fields {",
      "        name",
      "        type {",
      "          name",
      "        }",
      "      }",
      "    }",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    description: "Ignored recursive field with recursion guard enabled",
    id: "recursion",
    label: "Recursion Guard",
    options: {
      ignore: ["friends"],
      ignoreIntrospection: "typename",
      limitIgnoredRecursion: true,
      maxDepth: 3,
    },
    query: [
      "# Toggle 'Recursion Guard' to see the difference.",
      "# Without it, ignored recursive fields allow",
      "# unbounded depth since the counter never advances.",
      "query RecursiveIgnore {",
      '  user(id: "1") {',
      "    friends {",
      "      friends {",
      "        friends {",
      "          friends {",
      "            name",
      "          }",
      "        }",
      "      }",
      "    }",
      "  }",
      "}",
    ].join("\n"),
  },
  {
    description: "Basic user query well within the depth limit",
    id: "simple",
    label: "Simple",
    options: { ignore: [], ignoreIntrospection: "typename", maxDepth: 5 },
    query: [
      "query GetUser {",
      '  user(id: "1") {',
      "    name",
      "    posts {",
      "      title",
      "    }",
      "  }",
      "}",
    ].join("\n"),
  },
];
